"""fetch -> analyse -> generate. Nothing is written if validation fails; nothing is committed-worthy unless content changed."""
import datetime as dt
import os
from dataclasses import dataclass, field
from pathlib import Path

from .analytics import discovery
from .data import load_all
from .generators.markers import MarkerError, replace_blocks
from .generators.sections import Context, render_all
from .github.client import GitHubClient, GitHubError
from .github.fetch import fetch_contributions, fetch_repos
from .github.fixtures import FixtureClient
from .storage.cache import Cache, iso, parse_iso, would_change
from .validate import validate

FETCHED = ("repos", "activity", "releases", "contributions")


class BuildError(Exception):
    pass


@dataclass
class BuildResult:
    changed: bool
    blocks: dict
    warnings: list = field(default_factory=list)
    dry_run: bool = False


def utcnow():
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0)


def build(root, *, fixtures=False, dry_run=False, force=False, now=None, client=None) -> BuildResult:
    root = Path(root)
    now = now or utcnow()
    rep = validate(root)
    if not rep.ok:  # human error must be visible, and nothing gets written
        raise BuildError("validation failed:\n  " + "\n  ".join(rep.errors))
    data = load_all(root / "data")
    handle = data["profile"]["identity"]["handle"]
    cache = Cache(root / "data" / "cache")
    warnings: list[str] = []

    if client is None:
        if fixtures:
            client = FixtureClient(now, handle)
        else:
            token = os.environ.get("GITHUB_TOKEN")
            if not token:
                raise BuildError("GITHUB_TOKEN is not set (use --fixtures for an offline dry-run)")
            client = GitHubClient(token)

    fresh, api_ok = {}, {}
    try:
        fresh.update(fetch_repos(client, handle, now))
        api_ok["repos"] = True
    except GitHubError as e:
        api_ok["repos"] = False
        warnings.append(f"repos fetch failed, using last valid cache: {e}")
    try:
        fresh["contributions"] = fetch_contributions(client, handle, now)
        api_ok["contributions"] = True
    except GitHubError as e:
        api_ok["contributions"] = False
        warnings.append(f"contributions fetch failed, using last valid cache: {e}")

    # resolve each dataset: fresh -> last valid cache -> absent (section hidden, never fabricated)
    datasets, ages, snap = {}, {}, {}
    for name in FETCHED:
        if name in fresh:
            datasets[name], ages[name] = fresh[name], 0.0
        else:
            env = cache.read(name)
            if env and env.get("ok"):
                datasets[name], ages[name] = env["data"], Cache.age_hours(env, now)
                snap[name] = env["generated_at"][:10]

    # discovery (repo-list diff) — only advances when repos were freshly fetched
    prev_env = cache.read("discovery")
    prev_seen = prev_env["data"] if prev_env and prev_env.get("ok") else None
    first_seen = prev_seen or {}
    if "repos" in fresh:
        first_seen = discovery.update_first_seen(prev_seen, fresh["repos"], now)

    # cache writes (change-only) — skipped entirely on dry runs
    to_write = {n: fresh[n] for n in FETCHED if n in fresh}
    if "repos" in fresh:
        to_write["discovery"] = first_seen
    changed_data = [n for n, d in to_write.items() if would_change(cache, n, d)]
    gen_env = cache.read("generated_at")
    if changed_data:
        snapshot_date = now.date().isoformat()
    elif gen_env and gen_env.get("ok"):
        snapshot_date = parse_iso(gen_env["generated_at"]).date().isoformat()
    else:
        snapshot_date = now.date().isoformat()
    if not dry_run:
        for n in changed_data:
            cache.write(n, to_write[n], "github-graphql", now)
        if changed_data:
            cache.write("generated_at", {"api_ok": api_ok, "changed_at": iso(now)}, "profileos", now)

    # staleness label uses the cache's own date for datasets that fell back
    ctx_snapshot = min(snap.values()) if snap else snapshot_date
    ctx = Context(data, datasets, ages, now, ctx_snapshot if snap else snapshot_date, first_seen)
    blocks = render_all(ctx)
    if "FOOTER" in blocks and data["profile"].get("display", {}).get("show_freshness_stamp", True):
        blocks["FOOTER"] = f"<sub>Generated by ProfileOS · data snapshot {snapshot_date} · Automate facts. Curate identity.</sub>"
    warnings += ctx.warnings

    readme_path = root / "README.md"
    old = readme_path.read_text(encoding="utf-8")
    try:
        new, w = replace_blocks(old, blocks)
    except MarkerError as e:
        raise BuildError(f"README marker problem: {e}") from e
    warnings += w
    readme_changed = new != old
    if readme_changed and not dry_run:
        readme_path.write_text(new, encoding="utf-8")
    return BuildResult(changed=readme_changed or bool(changed_data), blocks=blocks, warnings=warnings, dry_run=dry_run)
